### ISSUE TITLE
how to provide proxy host and port to GooglePlayAPI ?

### ISSUE THREAD

**Issue by Artgit** [Akdeniz/google-play-crawler#12]
Hello, 

First of all I'd like to say thank you for this awesome library !

I want to work with this stuf in multithreading environment with a few concurrent GooglePlayAPI clients. Is it possible to setup different proxy hosts and ports to GooglePlayAPI clients ? If so, how it could be achieved ?

Thanks!

**Comment by Akdeniz** [comment]
Hi @Artgit ,

You should create HttpClients like this [function](https://github.com/Akdeniz/google-play-crawler/blob/master/src/main/java/com/akdeniz/googleplaycrawler/cli/googleplay.java#L556) and set it to GooglePlayerAPI with **setClient**.

**Comment by Artgit** [comment]
Hi @Artgit , thank you so much again for your awesome project !
