### ISSUE TITLE
Why do i need use GooglePlayAPI.uploadDeviceConfig() ?

### ISSUE THREAD

**Issue by Artgit** [Akdeniz/google-play-crawler#20]
It perfectly works without this method call. What is the purpose of this method ? Thanks.

**Comment by Akdeniz** [comment]
It is prerequisite for usegcm option and you don't need to call this method unless you need to use this option.
https://github.com/Akdeniz/google-play-crawler#about-account-page-registration

**Comment by Artgit** [comment]
@Akdeniz , thanks
