### ISSUE TITLE
ListResponse overrides final method getUnknownFields

### ISSUE THREAD

**Issue by qwertydzen** [Akdeniz/google-play-crawler#21]
HI!

Firstly, thank you for a great lib!

After update a version I have the error 
I work with library in jruby

After import com.akdeniz.googleplaycrawler.GooglePlayAPI

I have error in log

LoadError: load error: ./lib/google_play -- java.lang.VerifyError: class com.akdeniz.googleplaycrawler.GooglePlay$ListResponse overrides final method getUnknownFields.()Lcom/google/protobuf/UnknownFieldSet;
  require at org/jruby/RubyKernel.java:1027
   (root) at script/google_play.rb:8

May be do you know how it resolve?

**Comment by Akdeniz** [comment]
Hi @qwertydzen,

I think it is the issue of protobuf version.

Can you confirm that you are using version 2.5.0 of both protobuf compiler and library?

**Comment by qwertydzen** [comment]
<< aptitude show libprotobuf-java
Package: libprotobuf-java  
State: installed
Automatically installed: no
Version: 2.5.0-1chl1~lucid1
Priority: extra
Section: java
Maintainer: Ubuntu Developers ubuntu-devel-discuss@lists.ubuntu.com

<< protoc --version
libprotoc 2.5.0

I'm imported only your jar file and don't need compile one more time.
Your jar works well in cli mode but after include in jruby I catch error

Some else ideas?

**Comment by qwertydzen** [comment]
You said me about protobuf-java-2.5.0.jar after updating it all works well.
Thank you

**Comment by Fuzion24** [comment]
@Akdeniz, it might be a good idea to have sbt do some sanity checks on the environment to validate Protobuf is installed + correct version, etc..
