### ISSUE TITLE
Unable To Download App

### ISSUE THREAD

**Issue by saysach** [Akdeniz/google-play-crawler#26]
Hi,

I am able to Checkin, Register with the Credentials but when i try to download an app  i get error.

Error retrieving information from server. [RPC:S-5:AEC-0]·♣

**Comment by Akdeniz** [comment]
After `checkin` command, you are updating the `android` in configuration file, right? I only managed to get that error with wrong androidid!

**Comment by saysach** [comment]
yes is did the same, 

step a) Checked in with gmail user id and Password, in return i got the androidid and token
step b) updated the config file with android id and token
step c) fired the register command and got the success message.
step d) tried to download a package 

now it works, what i missed last time was to fire step c 

Will post if i see anyother thing,

Nice tool and good work!

**Comment by saysach** [comment]
sorry great work indeed!
