### ISSUE TITLE
getAuthorName() not work

### ISSUE THREAD

**Issue by hzzjucn** [Akdeniz/google-play-crawler#3]
Hi, Akdeniz
Thanks for your goolge play api.
I try to use it to crawl user reviews of apps.
I find that the method getAuthorName() for retrieving the author name of user reviews seems not work. I'm not sure if there are some bugs.

Best,
Ning

**Comment by Akdeniz** [comment]
Hi Ning,

It is because I use outdated version of Android-Finsky user agent to fetch HTTP request. 
I updated it to "Android-Finsky/3.10.14" with the last commit.

Review author can now be fetched like this : "getAuthor().getName()".

Regards

**Comment by hzzjucn** [comment]
Hi, Akdeniz
Thank you very much for your quick response.

Best,
Ning
