### ISSUE TITLE
No Response on Request

### ISSUE THREAD

**Issue by HenryHoggard** [Akdeniz/google-play-crawler#32]
The following request

POST /auth HTTP/1.1
Content-Length: 278
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Host: android.clients.google.com
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.2.2 (java 1.5)

Does not return a response anymore, Is this happening for anyone else?

**Comment by zawmn83** [comment]
I'm new to google play crawler and also new to java, when I tried below command, 0 result return.
root@######:/home/ubuntu/google-play-crawler-master/googleplay# java -jar googleplay.jar -f crawler.conf search games
Title;Package;Creator;Price;Installation Size;Number Of Downloads
Index: 0
I'm not sure is this related to this issue or not.

**Comment by HenryHoggard** [comment]
Seems to be working for me today.

**Comment by yaelma** [comment]
can you please explain how? did you change anything?

**Comment by HenryHoggard** [comment]
Your account is probably banned, that is what happened in this instance iirc.
