### ISSUE TITLE
AndroidID, Security Token etc.. gor a client - server flow

### ISSUE THREAD

**Issue by raulraja** [Akdeniz/google-play-crawler#38]
Trying to wrap my head around the whole Android_ID, autogeneration etc...
We have a server with the google play crawler where I can successfully serve all the operations via REST endpoints to be consumed by clients connecting to the REST API.

Obviously the user / password constructor then checkin() is not an option for this case.
We want to use the clients access to google accounts to provide our Android id, secretToken and cd2m auth token so each client has it's own GooglePlayAPI instance associated to the account that use for the requests.

What is the recommended flow approach to use the GooglePlayAPI class without a user and pass?

The checkin() call implies you have a password instance variable.

Any ideas on how to implement such a flow? thanks in advance and great job.

**Comment by Akdeniz** [comment]
Assuming your client lives as an android app, you can try this..

http://www.demirozali.com/?p=76

**Comment by raulraja** [comment]
Thanks @Akdeniz I succeeded getting a AC2DM token and Android ID based on your post! . It complains about the security token though not being valid when I perform requests with those credentials. As I understand the security token is generated when you first call checkin() and that call uses the fake S3 info hardcoded in the lib. Is there any way to obtain the security token from the clients? thx

**Comment by raulraja** [comment]
Nevermind I figured it out, just needed those two fields, thanks
