### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by slojo** [Akdeniz/google-play-crawler#41]
Tried installing the project several times. 

At first, thought it was a scala/sbt version problem but after several tries, I always end up with this error 

| private Queue<T> filteredMessages = new ConcurrentLinkedDeque<>()

Any suggestions?

OS: Ubuntu 12.04

**Comment by ashishb** [comment]
Are you on Mac?
I got the same error on Mac, the fix for me was to install Sun Java (brew cask install java) which install JDK7, default version on Mac is JDK6.

**Comment by slojo** [comment]
Hi, 

As mentioned in the issue, I'm on Ubuntu 12.04
I did replace my java installation with a Sun installation. 

That does indeed get rid of the previous error however, I have a new error now. 

"TestGooglePlayCrawler.java:16: error: package org.testng does not exist
[error] import org.testng.Assert;
[error]                  ^"
..among several other errors. 

Is there something I'm missing as part of the requirements?
The Readme installation seems pretty straightforward, however I've been struggling with the installation for a week now.

My current Java version is :
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) Server VM (build 24.51-b03, mixed mode)

**Comment by ashishb** [comment]
Exact same issue here, the previous error went away and I got the exact same new error now.

**Comment by Akdeniz** [comment]
I think that is because of non-existing testng dependency in Build.scala. Just merged @raulraja's pull request. That should have solved the problem.

**Comment by slojo** [comment]
Thanks! It works perfectly fine now.

Real good work in there btw! We've been trying to find an automated process for Google play account creation for a while now. This works great!!
