### ISSUE TITLE
cannot build with Sbt : MessageFIlter  Illegal start of type ERROR

### ISSUE THREAD

**Issue by ahikmat85** [Akdeniz/google-play-crawler#54]
[info] Compiling 20 Java sources to /Users/ahikmat/Documents/kh/crawler/google-play-crawler-master/target/scala-2.9.2/classes...
[error] /Users/ahikmat/Documents/kh/crawler/google-play-crawler-master/src/main/java/com/akdeniz/googleplaycrawler/gsf/MessageFilter.java:18: illegal start of type
[error]     private Queue<T> filteredMessages = new ConcurrentLinkedDeque<>();
[error]                                                                   ^
[error] 1 error
[error](compile:compile) javac returned nonzero exit code
[error] Total time: 135 s, completed May 27, 2014 10:54:06 AM

**Comment by Fuzion24** [comment]
What java version are you using?  Try Java7.

**Comment by ahikmat85** [comment]
I was using Java1.6

updated to Java 1.7, now it builds without problem
Thank you!
