### ISSUE TITLE
How to use subcommand "list" right?

### ISSUE THREAD

**Issue by BearTi** [Akdeniz/google-play-crawler#6]
Hi,

I´ve problems with the use of "java -jar googleplay.jar list".
I don´t know how to use it right.

I want to have (for example) the top 50 apps of each category (free apps).

Here´s my command:
"java -jar gooleplay.jar -f crawler.conf list -s tools category" 
=> I get: "↕6↕4Error retrieving information from server. [DF-LA-02]↨☻"
But I can download app without probelems...

Can anyone give me an example?
Thanks :-)

**Comment by Akdeniz** [comment]
**java -jar googleplay.jar -f crawler.conf categories** 
lists available categories.(ID and Name)
**java -jar googleplay.jar -f crawler.conf list TOOLS**
lists available sub-categories under **TOOLS** category.(ID and Title)
**java -jar googleplay.jar -f crawler.conf list TOOLS -s apps_topselling_paid**
list applications of **TOOLS** category and **apps_topselling_paid** sub-category.

You should use IDs of category and sub-categories those you want to use.

**Comment by BearTi** [comment]
Thanks a lot! It´s works perfect! :-D
