### ISSUE TITLE
Please Fix That: Cannot download complete apk

### ISSUE THREAD

**Issue by djxhero** [Akdeniz/google-play-crawler#60]
https://play.google.com/store/apps/details?id=com.bandainamcogames.pacfriends
This app's package size suppose to be  63.13MB .
But when I use your code to  download  apk ——It gets only 12MB

May be this app include "install package" and "data package".
 And your code just can download "install package".
Am I right? Or other reasons.

How to fix that?

**Comment by winkar** [comment]
Same problem .Always halt with "SSL peer shut down incorrectly" error message
