### ISSUE TITLE
Set proxy in TestGooglePlay.java

### ISSUE THREAD

**Issue by BearTi** [Akdeniz/google-play-crawler#7]
Hi,

how can I set a proxy in the "TestGooglePlay.java" class?
I set it in the crawler.conf, but I think this class don´t gets anxy information from the conf-file, right?

Thanks

**Comment by Akdeniz** [comment]
You can create an HttpClient as in [this](https://github.com/Akdeniz/google-play-crawler/blob/master/src/com/akdeniz/googleplaycrawler/cli/googleplay.java#L522) function and set it to GooglePlayAPI instance with **setClient**.
