### ISSUE TITLE
No results when using in a Java program

### ISSUE THREAD

**Issue by guenodz** [Akdeniz/google-play-crawler#75]
Hello,

i have used google-play-crawler in my java program, but nothing is returned.
here my program:

``` java
public static void main(String[] args) throws Exception {

        GooglePlayAPI playAPI = new GooglePlayAPI("email", "pass", "android_id");
        playAPI.setClient(new DefaultHttpClient());
        playAPI.login();

        GooglePlay.DetailsResponse response = playAPI.details("packag_name");
        System.out.println(response.toString());
    }
```

And when i debug the program, all reponse's attributes are empty.

**Comment by GitTom** [comment]
Yes, if you look at this issue:  https://github.com/Akdeniz/google-play-crawler/issues/69

I think that the project is not working since about 6 months.

Also, the other Java based play store api's that I'm aware of are abandoned and broken too.

**Comment by guenodz** [comment]
Thanks @GitTom  :+1:
