### ISSUE TITLE
Google Account disabled

### ISSUE THREAD

**Issue by BearTi** [Akdeniz/google-play-crawler#8]
Hi,

my test google account for this api was disabled by google.
I think because I used this API to often? Is that possible?

How can I avoid this in future and should I just reactivate my account by let sending me a verification code via sms?

thanks

**Comment by Akdeniz** [comment]
Hi @BearTi,

It is a known consequence of intensive usage of this api. It is one of the defensive mechanism of google play servers. To avoid this, you can always create several google account and use them levelly. 

There is no harm to verify your account with your mobile phone number. Google use given phone number only for verification and does not correlate it with your account as stated [here](http://support.google.com/accounts/bin/answer.py?hl=en&answer=114129)
